---
title: "R Notebook"
output:
  word_document: default
  pdf_document: default
  html_notebook: default
---
# 1.paste

```{r}

# 指定分隔符连接多个字符串
# 输出结果："R-is-fun"

paste("Hello", "world")
```

```{r}
# 指定分隔符连接多个字符串
# 输出结果："R-is-fun"

paste("R", "is", "fun", sep = "-")
```

```{r}
# 连接向量中的元素
# 输出结果："apple, banana, orange"

x <- c("apple", "banana", "orange")
paste(x, collapse = ", ")
```

```{r}
# 使用 sep 和 collapse 参数
# 输出结果："I have 3 fruits: apple, banana, orange"

fruits <- c("apple", "banana", "orange")
paste("I have", length(fruits), "fruits:", paste(fruits, collapse = ", "))
```

# 2.paste0

```{r}
# 将文本字符串连接起来，无分隔符
paste0("Hello", "world")
# 输出结果："Helloworld"

# 连接向量中的元素，无分隔符
x <- c("apple", "banana", "orange")
paste0(x)
# 输出结果："applebananaorange"

```

```{r}
# 使用 paste0 连接字符串和变量
name <- "Alice"
age <- 30
paste0("Name: ", name, ", Age: ", age)
# 输出结果："Name: Alice, Age: 30"

# 连接向量的元素
fruits <- c("apple", "banana", "orange")
paste0("Fruits: ", fruits)
# 输出结果："Fruits: apple" "Fruits: banana" "Fruits: orange"

```
# merge
```{r}
merge(x, y, by = NULL, by.x = NULL, by.y = NULL,
      all = FALSE, all.x = FALSE, all.y = FALSE,
      sort = TRUE)
#参数说明：
#x, y：要合并的两个数据框或列表。
#by：指定连接的变量名称，可以是一个字符向量，表示在哪些列上进行连接。默认为 NULL，此时会自动寻找两个数据框中共有的列名进行连接。
#by.x, by.y：分别指定 x 数据框和 y 数据框中用于连接的列名。如果 by 参数未指定，则会根据这两个参数进行连接。
#all, all.x, all.y：逻辑值，控制是否保留未匹配的数据。all 为 TRUE 表示保留所有行（外连接），FALSE 则只保留匹配的行（内连接）。
#sort：逻辑值，是否根据连接键对结果进行排序，默认为 TRUE。

# 创建数据框 df1 和 df2
df1 <- data.frame(ID = 1:3,
                  Name = c("Alice", "Bob", "Charlie"))
df2 <- data.frame(ID = 2:4,
                  Age = c(25, 30, 35))

# 使用 merge() 函数合并数据框
merged_df <- merge(df1, df2, by = "ID")

# 输出合并后的结果
print(merged_df)

# 外连接，保留所有行
merged_all <- merge(df1, df2, by = "ID", all = TRUE)

# 左连接，保留 df1 的所有行
merged_left <- merge(df1, df2, by = "ID", all.x = TRUE)

```
# aggregate()
```{r}
#基本语法
aggregate(formula, data, FUN)
#formula：指定需要聚合的列和聚合的方式。一般形式为 y ~ x1 + x2 + ...，其中 y 是需要聚合的列，x1, x2, ... 是分组变量。使用 formula 参数时，~ 左边是需要聚合的数值型变量，右边是分组的变量。

#data：指定进行操作的数据框。

#FUN：指定应用于数据的函数，可以是内置的聚合函数（如 sum, mean, median, max, min 等），也可以是用户自定义的函数。

df <- data.frame(
  Student = c("A", "B", "C", "A", "B"),
  Score = c(80, 75, 90, 85, 82),
  Grade = c("A", "B", "A", "B", "B")
)
# 按grade列对学生成绩进行分组
aggregate(Score ~ Grade, data = df, FUN = mean)
# 按照多个列进行聚合 ？？？不太懂
aggregate(Score ~ Grade + Student, data = df, FUN = max)
# 使用自定义函数进行聚合
my_summary <- function(x) {
  c(median = median(x), sd = sd(x))
}
aggregate(Score ~ Grade, data = df, FUN = my_summary)



```

